			console.log(
				'(',
					(Warehouser._Locked === true), 'OR (',
						(Waiting === 0), 'AND',
						(Warehouser.Bundling.AllowEmpty != true),
					')[',
						((Warehouser.Bundling.AllowEmpty != true) && (Waiting === 0)),
					']',
					'OR (',
						'(',
							((Now % Warehouser.Bundling.Window) !== 0), 'AND',
							(Waiting != Warehouser.Bundling.Limit),
						') OR (',
							(Waiting < Warehouser.Bundling.Limit),
							((Now - Warehouser._LastRun) < Warehouser.Bundling.Window),
						')[',
							((Now % Warehouser.Bundling.Window) !== 0) || ((Waiting < Warehouser.Bundling.Limit) && ((Now - Warehouser._LastRun) < Warehouser.Bundling.Window)),
						']',
					')[',
						(((Now % Warehouser.Bundling.Window) !== 0) || ((Waiting < Warehouser.Bundling.Limit) && ((Now - Warehouser._LastRun) < Warehouser.Bundling.Window))),
					']',
				')[',
					((Warehouser._Locked === true) || (((Waiting === 0) && (Warehouser.Bundling.AllowEmpty != true))) || (((Now % Warehouser.Bundling.Window) !== 0) || ((Waiting < Warehouser.Bundling.Limit) && ((Now - Warehouser._LastRun) < Warehouser.Bundling.Window)))),
				']'
			);